# Generated by Django 4.2.6 on 2023-10-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('icon', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind', models.FloatField()),
                ('sunrise_timestamp', models.CharField(max_length=10)),
                ('sunset_timestamp', models.CharField(max_length=10)),
                ('duration_of_the_day', models.DurationField()),
            ],
        ),
    ]
